# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: "3.8"

networks:
  docker_nw:
    driver: bridge

services:
  db:
    container_name: $CONTAINER_NAME_DB
    image: $IMAGE_NAME_DB_ACTUAL
    restart: unless-stopped
    volumes:
      - ./resources/mysql.cnf:/etc/mysql/conf.d/config-file.cnf
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PW
      - MYSQL_ROOT_PASSWORD=$DB_PW
      - MYSQL_DATABASE=$DB_NAME
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e "SELECT 1" >/dev/null 2>&1;'
        ]
      interval: 1s
      timeout: 10s
      retries: 30
    networks:
      docker_nw: